#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the subshell. For example:
#           /bin/sh -c 'export SHELL=/bin/bash; exec /bin/bash /path/to/gradlew'
#       The above example illustrates running gradlew with Bash as the subshell,
#       but many systems do not have Bash in /bin/sh. For instance, Debian
#       and Ubuntu use Dash, which is POSIX-compliant. In that case, you can
#       simply run 'sh gradlew' at the prompt.
#
#       The above example also illustrates that you need to export the SHELL
#       environment variable to the setting of your preferred shell. This is
#       necessary because Gradle uses the 'shell' builtin to execute commands
#       in subprocesses. In POSIX, the 'shell' builtin is required to use
#       the "SHELL" environment variable if it exists, if not, it falls back
#       to '/bin/sh'. If you do not set the SHELL variable, Gradle might try
#       to use '/bin/sh' where Bash is not located. This can cause errors. 
#
#       If you are certain that your system supports running '/bin/sh' with Bash,
#       then you can set the SHELL environment variable to '/bin/bash'. However,
#       this is not recommended because the Gradle project cannot guarantee
#       that Bash is supported on all systems. We even state in the public
#       Gradle issue tracker that we do not support using the 'shell' builtin
#       with Bash due to its inconsistent behavior. For more information,
#       see https://github.com/gradle/gradle/issues/18833. If you still
#       want to use Bash, set the SHELL environment variable.
#
#   (2) System name and version detection relies on 'uname'. 'uname' is not
#       available on every system. If you have problems, check your OS and
#       use 'gradlew' on the command line rather than 'sh gradlew'.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Use the maximum available file descriptors if 'ulimit' supports it
if command -v ulimit > /dev/null 2>&1; then
    ulimit -n 4096
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command, setting the classpath and the wrapper jar.
# * $APP_HOME/gradle/wrapper/gradle-wrapper.jar (the wrapper jar).
# * $APP_HOME/gradle/wrapper/gradle-wrapper.properties (the wrapper properties).
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xjava" command is not found.
if ! command -v java > /dev/null 2>&1
then
    echo "Error: 'java' command not found. Please install Java (openjdk-17) and try again." >&2
    exit 1
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "Error: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || echo "Error: 'java' command not found in PATH. Please install Java (openjdk-17) and set JAVA_HOME." >&2
fi

# Increase the maximum file descriptors if we can.
if ! "$JAVACMD" -XshowSettings:properties -version 2>/dev/null | grep -q 'sun.io.compression.enabled = true'; then
    # Not using 'ulimit' because it might not be available.
    if command -v ulimit > /dev/null 2>&1; then
        ulimit -n 4096
    fi
fi

# Execute the wrapper, passing through all arguments.
exec "$JAVACMD" "$@"
